@startuml 23 - Customer - Remove shipment address

autonumber
autoactivate on

actor Customer as Actor
boundary Form
control AccountController as Controller
participant ShipmentService as Service
participant AddressRepository as Repo
participant ProjectDbContext as Context
database Database

Actor -> Form: AddressId
Form -> Controller: HttpRequest
Controller -> Service: RemoveAddressAsync
Service -> Repo: RemoveAsync
Repo -> Context: RemoveAsync
Context -> Database: Delete
Database --> Context: status
Context --> Repo: status
Repo --> Service: status
Service --> Controller: status
Controller --> Form: Response
Form --> Actor: status

@enduml