@startuml 25 - Customer - Add product to cart

autonumber
autoactivate on

actor Customer as Actor
boundary Form
control CartController as Controller
participant CartService as Service
participant CartRepository as Repo
participant ProjectDbContext as Context
database Database

Actor -> Form: Product\nQuantity
Form -> Controller: HttpRequest
Controller -> Service: AddProductAsync
Service -> Repo: AddAsync
Repo -> Context: AddAsync
Context -> Database: Insert
Database --> Context: status
Context --> Repo: status
Repo --> Service: status
Service --> Controller: status
Controller --> Form: Response
Form --> Actor: status

@enduml